### ISSUE TITLE
expr in data binding errors out after so many iterations

### ISSUE THREAD

**Issue by jeromatron** [nosqlbench/nosqlbench#195] opened 2020-08-20 03:07 UTC
**Describe the bug**
This binding seems to have issues after a certain iteration:

```Uniform(1.00d,100.00d); Expr('new java.text.DecimalFormat(".##").format(cycle)'); ToFloat()```

**To Reproduce**
1. create a data binding with the above expression.
2. run it with stdout for 1000 cycles.
3. will get something like the following stack trace after some number of cycles:

```
);**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
Expression: null
13:01:55.446 [./repro:001] ERROR i.n.e.a.activityimpl.motor.CoreMotor - Error in core motor loop:java.lang.VerifyError: (class: ASMAccessorImpl_134194056615978925154315, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
java.lang.VerifyError: (class: ASMAccessorImpl_134194056615978925154315, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3215)
	at java.base/java.lang.Class.getConstructor0(Class.java:3420)
	at java.base/java.lang.Class.getConstructor(Class.java:2165)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:766)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeObjectCreation(ASMAccessorOptimizer.java:3184)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:98)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
	at org.mvel2.ast.NewObjectNode.getReducedValueAccelerated(NewObjectNode.java:237)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:968)
	at org.mvel2.MVEL.executeExpression(MVEL.java:1003)
	at io.nosqlbench.virtdata.library.basics.shared.from_double.to_double.Expr.applyAsDouble(Expr.java:38)
	at io.nosqlbench.virtdata.core.composers.ComposerForLongToDoubleFunction.lambda$andThen$9(ComposerForLongToDoubleFunction.java:66)
	at io.nosqlbench.virtdata.core.composers.ComposerForLongToDoubleFunction.lambda$andThen$12(ComposerForLongToDoubleFunction.java:78)
	at io.nosqlbench.virtdata.core.bindings.Bindings.get(Bindings.java:220)
	at io.nosqlbench.virtdata.core.templates.StringCompositor.bindValues(StringCompositor.java:112)
	at io.nosqlbench.virtdata.core.templates.StringBindings.bind(StringBindings.java:26)
	at io.nosqlbench.activitytype.stdout.StdoutAction.runCycle(StdoutAction.java:53)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Here is a yaml for reproducing:

```
description: repro
bindings:
  key: Mod(1000000000000L); ToString()
  value: Uniform(1.00d,100.00d); Expr('new java.text.DecimalFormat(".##").format(cycle)'); ToFloat()
blocks:
  - tags:
      phase: schema
    params:
      prepared: false
    statements:
      - create-table: |-
          CREATE TABLE IF NOT EXISTS <<keyspace:keyspace1>>.table1 (
          key text,
          key float,
          PRIMARY KEY ((key))
          );
  - tags:
      phase: rampup
    params:
      cl: '<<write_cl:LOCAL_QUORUM>>'
      instrument: true
    statements:
      - insert-rampup: |-
          INSERT INTO <<keyspace:keyspace1>>.table1 (
          key,
          value
          ) VALUES (
          {key},
          {value},
          );
```

Then do something like

```
nb run driver=stdout workload=./repro cycles=1000
```

**Comment by jshook** [comment] 2020-09-03 23:03
This was due to an issue with Java versions in an older MVEL dependency. A fix is pending for release.

**Comment by jshook** [comment] 2020-09-10 23:05
The fix for this has been verified. I was able to do this easily due to the detailed reproduction steps in the issue. Thanks for doing that!

**Closed by jshook** 2020-09-10 23:05 UTC
