### ISSUE TITLE
"keyspace" parameter not picked up by workload "cql-keyvalue" in v4.15.82

### ISSUE THREAD

**Issue by hemidactylus** [nosqlbench/nosqlbench#406] opened 2022-01-18 15:49 UTC
**Describe the bug**
It seems that, at least for `cql-keyvalue` workload, the command-line parameter "keyspace" is ignored in recent versions of NoSQLBench. This was not the case until at least 4.15.64 and happens for 4.15.82 (I don't know where exactly the behaviour started).

**To Reproduce**
1. Run something like `cql-keyvalue default driver=stdout main-cycles=10 rampup-cycles=10 keyspace=myKeyspace` and inspect the statement being printed.
2. On a version <= 4.15.64 one sees output such as `select * from myKeyspace.keyvalue where key=319317307;`
3. On a recent version one sees `select * from baselines.keyvalue where key=198265640;` despite having used the very same command-line (including the `keyspace=myKeyspace` parameter).

**What was Expected**
I assume the intended behaviour is for the `keyspace` parameter to be still read from the command-line provided values (so, `myKeyspace` in the example above).

**Additional context**
On _any_ version (even the most up-to-date one), when invoking with `--show-script`, the output correctly includes `'keyspace':      'myKeyspace',` in all the `scenario.run(...` invocations it produces.

**Comment by jshook** [comment] 2022-01-18 17:27
@hemidactylus I have added a set of tests for this at the doc level (not including named scenarios). It wasn't reproducible there, so I believe the issue is with the way that named scenarios and template vars work together. I'll add another set of tests to cover this case as well.

**Comment by jshook** [comment] 2022-01-21 18:36
This fix was added to the 4.17 pre-release track. I'm porting the fixes into the 4.15 main release branch too.

**Comment by jshook** [comment] 2022-01-31 19:49
@hemidactylus This fix is in both 4.15.* and 4.17.* branches now. The latest 4.15.* release should be fixed. Can you test this and verify when you get a chance?

**Closed by jshook** 2022-01-31 19:49 UTC
Labels: blocker

**Comment by hemidactylus** [comment] 2022-02-02 11:26
I just tested with 4.15.86 and it all works (both with driver=stdout and cql), thank you!

**Comment by jshook** [comment] 2022-02-02 15:56
Thanks for the closure!

**Comment by jshook** [comment] 2023-02-07 18:45
@all-contributors please add @hemidactylus for community support, workshops, bug reports, and bugfixes
