### ISSUE TITLE
invalid error handler value should be rejected by the CLI immediately

### ISSUE THREAD

**Issue by XN137** [nosqlbench/nosqlbench#274] opened 2021-03-01 08:29 UTC
**Describe the bug**
using the following command where "count" is an invalid error handler:
```
nb run alias=main-test type=http yaml=http-iot tags=phase:main rate=400000 threads=2000 errors=count host=10.101.33.114,10.101.34.44,10.101.33.216 cycles=0..5000000 -v (...)
```

then the run starts and the log is full of errors like this:
```
 6222 ERROR [rampup:207] CoreMotor    Error in core motor loop:java.lang.RuntimeException: ErrorHandler named 'count' could not be found in [meter, stop, retry, ignore, warn, counter, histogram, code, timer]
java.lang.RuntimeException: ErrorHandler named 'count' could not be found in [meter, stop, retry, ignore, warn, counter, histogram, code, timer]
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.getHandler(NBErrorHandler.java:73)
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.lookup(NBErrorHandler.java:56)
	at io.nosqlbench.engine.api.activityapi.errorhandling.modular.NBErrorHandler.handleError(NBErrorHandler.java:37)
	at io.nosqlbench.activitytype.http.HttpAction.runCycle(HttpAction.java:128)
	at io.nosqlbench.engine.api.activityimpl.motor.CoreMotor.run(CoreMotor.java:415)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**What was Expected**

the CLI should reject this command immediately and ask the user to use a correct value for the `errors` parameter

side note:
it would probably also make sense to log the following things at the beginning of a NB run:
- version of NB
- full given command line

**Comment by jshook** [comment] 2021-03-11 23:22
@XN137 Just some updates on this so far...
The current release now has version logging (info level) as well as client hardware specs (also info level). The full command line is also logged via the annotations feature, which records life-cycles and metadata at various points in a test. One of the annotator implementations is the "log annotator" which captures the scenario commands in their initial format.

The main issue above is not complete, so I'm not closing this issue yet.

**Comment by dave2wave** [comment] 2024-10-15 22:43
Since this issue was raised there is now an ErrorHandler for `count`.

In `NBErrorHandler` it looks like all missing handlers and other objects do cause meaningful error messages. Unless the need extra effort is better explained then I think that this issue should be closed.

**Comment by dave2wave** [comment] 2024-11-12 21:21
Cannot reproduce.

**Closed by dave2wave** 2024-11-12 21:21 UTC
Labels: validated
