### ISSUE TITLE
template variables in scripts should be allowed with strict parameter checking

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1070] opened 2023-02-08 16:11 UTC
With strict parameter checking, template variables may only be used as such, and any overlaps between these and actual activity parameters is verbotten.

This is not always appropriate, and in some cases is counterintuitive.

When the settings from #12 are in relaxed mode, this should be allowed. In strict mode, they separate between these should still be enforced.

**Comment by dave2wave** [comment] 2024-11-07 15:42
We need to understand this from the perspective of how `StrInterpolation` works.
1. Is it the correct order with CmdParams first?

**Comment by dave2wave** [comment] 2024-11-15 20:17
Near duplicate of #117

**Comment by dave2wave** [comment] 2024-11-19 19:03
Hosted scripting runtimes are no longer supported like Nashorn and GraalJS. CLI scripting is still supported.

**Closed by dave2wave** 2024-11-19 19:03 UTC
Labels: meta-programming, validated, needs implentation discussion
